### PR TITLE
Update spdlog to track v1.x branch (v1.4)

### PR DESCRIPTION
**Pull request by kuzi117**
Spdlog in the aegis repository is very behind, this pull request moves it forward.

### CODE REVIEW

**Comment by kuzi117** [comment]
My main problem right now is regarding what to do with FindSpdlog.cmake. I've updated it for the new version but I'm not sure what to do with it. When installed, spdlog provides a config file that works for me so I don't know what purpose the find file has now.

That being said, the build is currently failing because it can't find spdlog. I've looked into it and realised that the buildbot isn't building the subprojects which means that the config cmake is never generated.

I'm waiting on a decision from you to move forwards with this.

**Comment by zeroxs** [comment]
The set up now requires that spdlog already exist on the system. The way aegis works is that if it doesn't exist, the FindSpdlog will fall back to the git submodule directory. Yours is failing though because now there is no Find* file for it to even hope to set a directory. The solution would be to keep using the FindSpdlog it has, make a new one, or configure and install spdlog before aegis attempts to configure so that it can find it on the CI. That presents a new requirement for users of the lib though. Now it'll require installing spdlog no matter what.

**Comment by kuzi117** [comment]
This is what I was hoping to get out of the discussion. I didn't realise this was a requirement you had in mind. So you are hoping to keep using `find_package` in `MODULE` mode. I need to look into how to look for the real spdlogConfig if it exists because I'd prefer that create its targets rather than manually creating them.

**Comment by braindigitalis** [comment]
The newer spdlog builds a lot faster. The fmt::format that comes with it can be built without header-only which massively decreases the build time of aegis. If we can find a way to make this work, we should imho.

**Comment by zeroxs** [comment]
Went ahead and did this with https://github.com/zeroxs/aegis.cpp/commit/536b3d4587fa0e83104c9455e5ffd66d7041dcdc

**Pull request closed without merging**
